# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Daniel\git\SnapSort\SnapSort/gui\renameDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mainwin(object):
    def setupUi(self, Mainwin):
        Mainwin.setObjectName("Mainwin")
        Mainwin.resize(740, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Mainwin.sizePolicy().hasHeightForWidth())
        Mainwin.setSizePolicy(sizePolicy)
        Mainwin.setMinimumSize(QtCore.QSize(740, 200))
        Mainwin.setMaximumSize(QtCore.QSize(740, 200))
        self.renameButton = QtWidgets.QPushButton(Mainwin)
        self.renameButton.setGeometry(QtCore.QRect(290, 127, 91, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renameButton.sizePolicy().hasHeightForWidth())
        self.renameButton.setSizePolicy(sizePolicy)
        self.renameButton.setObjectName("renameButton")
        self.dateEdit = QtWidgets.QLineEdit(Mainwin)
        self.dateEdit.setGeometry(QtCore.QRect(290, 26, 81, 20))
        self.dateEdit.setMaxLength(10)
        self.dateEdit.setPlaceholderText("")
        self.dateEdit.setObjectName("dateEdit")
        self.sectionBox = QtWidgets.QComboBox(Mainwin)
        self.sectionBox.setGeometry(QtCore.QRect(388, 26, 71, 22))
        self.sectionBox.setObjectName("sectionBox")
        self.fileListWidget = QtWidgets.QListWidget(Mainwin)
        self.fileListWidget.setGeometry(QtCore.QRect(10, 26, 251, 141))
        self.fileListWidget.setObjectName("fileListWidget")
        self.descriptionEdit = QtWidgets.QLineEdit(Mainwin)
        self.descriptionEdit.setGeometry(QtCore.QRect(470, 26, 261, 20))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.descriptionSuggestions = QtWidgets.QTableWidget(Mainwin)
        self.descriptionSuggestions.setGeometry(QtCore.QRect(470, 46, 261, 121))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.descriptionSuggestions.setFont(font)
        self.descriptionSuggestions.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.descriptionSuggestions.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.descriptionSuggestions.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descriptionSuggestions.setAutoScroll(False)
        self.descriptionSuggestions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.descriptionSuggestions.setTabKeyNavigation(False)
        self.descriptionSuggestions.setProperty("showDropIndicator", False)
        self.descriptionSuggestions.setDragDropOverwriteMode(False)
        self.descriptionSuggestions.setAlternatingRowColors(False)
        self.descriptionSuggestions.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.descriptionSuggestions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.descriptionSuggestions.setShowGrid(True)
        self.descriptionSuggestions.setGridStyle(QtCore.Qt.DotLine)
        self.descriptionSuggestions.setWordWrap(False)
        self.descriptionSuggestions.setCornerButtonEnabled(False)
        self.descriptionSuggestions.setRowCount(10)
        self.descriptionSuggestions.setColumnCount(2)
        self.descriptionSuggestions.setObjectName("descriptionSuggestions")
        self.descriptionSuggestions.horizontalHeader().setVisible(False)
        self.descriptionSuggestions.horizontalHeader().setCascadingSectionResizes(False)
        self.descriptionSuggestions.horizontalHeader().setDefaultSectionSize(200)
        self.descriptionSuggestions.horizontalHeader().setStretchLastSection(True)
        self.descriptionSuggestions.verticalHeader().setVisible(False)
        self.descriptionSuggestions.verticalHeader().setCascadingSectionResizes(True)
        self.descriptionSuggestions.verticalHeader().setDefaultSectionSize(18)
        self.descriptionSuggestions.verticalHeader().setHighlightSections(False)
        self.descriptionSuggestions.verticalHeader().setMinimumSectionSize(18)
        self.label = QtWidgets.QLabel(Mainwin)
        self.label.setGeometry(QtCore.QRect(291, 12, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Mainwin)
        self.label_2.setGeometry(QtCore.QRect(389, 12, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Mainwin)
        self.label_3.setGeometry(QtCore.QRect(472, 10, 141, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Mainwin)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_4.setObjectName("label_4")
        self.line_2 = QtWidgets.QFrame(Mainwin)
        self.line_2.setGeometry(QtCore.QRect(0, 170, 741, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtWidgets.QLabel(Mainwin)
        self.label_6.setGeometry(QtCore.QRect(323, 12, 47, 13))
        self.label_6.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Mainwin)
        self.label_7.setGeometry(QtCore.QRect(440, 9, 21, 20))
        self.label_7.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Mainwin)
        self.label_8.setGeometry(QtCore.QRect(683, 12, 47, 13))
        self.label_8.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Mainwin)
        self.label_9.setGeometry(QtCore.QRect(290, 110, 91, 16))
        self.label_9.setStyleSheet("color: rgb(180, 180, 180);")
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Mainwin)
        QtCore.QMetaObject.connectSlotsByName(Mainwin)
        Mainwin.setTabOrder(self.fileListWidget, self.dateEdit)
        Mainwin.setTabOrder(self.dateEdit, self.sectionBox)
        Mainwin.setTabOrder(self.sectionBox, self.descriptionEdit)
        Mainwin.setTabOrder(self.descriptionEdit, self.renameButton)
        Mainwin.setTabOrder(self.renameButton, self.descriptionSuggestions)

    def retranslateUi(self, Mainwin):
        _translate = QtCore.QCoreApplication.translate
        Mainwin.setWindowTitle(_translate("Mainwin", "Form"))
        self.renameButton.setText(_translate("Mainwin", "Umbenennen"))
        self.label.setText(_translate("Mainwin", "Datum"))
        self.label_2.setText(_translate("Mainwin", "Abschnitt"))
        self.label_3.setText(_translate("Mainwin", "Beschreibung"))
        self.label_4.setText(_translate("Mainwin", "Warteschlange"))
        self.label_6.setText(_translate("Mainwin", "[F1]"))
        self.label_7.setText(_translate("Mainwin", "[F2]"))
        self.label_8.setText(_translate("Mainwin", "[F3]"))
        self.label_9.setText(_translate("Mainwin", "[STRG+Enter]"))

